#版本信息
version: '3'
#服务
services:
  #docker运行时的实例名
  ofo-db: #数据库服务
    #镜像地址
    image: asdf1221/ofo-db:v0.1
    #restart: always
    #启动参数,设置密码为1234
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=1234
    #端口号
    ports:
      - 3306:3306
    networks: #使用自定义的网络信息，默认是安装docker时的bridge(加入同一个网段，各个服务就能通过实例名称去调用)
      - ofo-network
  ofo-redis: #缓存数据库服务
      #镜像地址
      image: asdf1221/ofo-db:v0.1
      #端口号
      ports:
        - 6379:6379
      networks:
        - ofo-network
  eureka0:  #eureka集群注册中心
      #镜像地址
      image: asdf1221/ofo-eureka0:v0.1
      ports:
        - 8081:8081
      networks:
        - ofo-network
  eureka1: #eureka集群注册中心1
      #镜像地址
      image: asdf1221/ofo-eureka1:v0.1
      ports:
        - 8082:8082
      networks:
        - ofo-network
  eureka2: #eureka集群注册中心2
      image: asdf1221/ofo-eureka2:v0.1
      ports:
        - 8083:8083
      networks:
        - ofo-network
  ofo-services0: #services服务
      image: asdf1221/ofo-service0:v0.1
      #depends_on: #设置启动数据库服务后再启动容器服务，防止找不到数据库服务报错
       # - ofo-db
        #- ofo-redis
      ports:
        - 8011:8011
      networks:
        - ofo-network
  ofo-services1: #services服务
    image: asdf1221/ofo-service1:v0.1
   # depends_on: #设置启动数据库服务后再启动容器服务，防止找不到数据库服务报错
     # - ofo-db
     # - ofo-redis
    ports:
      - 8012:8012
    networks:
      - ofo-network
  ofo-services2: #services服务
    image: asdf1221/ofo-service2:v0.1
      # depends_on: #设置启动数据库服务后再启动容器服务，防止找不到数据库服务报错
    # - ofo-db
    # - ofo-redis
    ports:
      - 8013:8013
    networks:
      - ofo-network
  ofo-feign0: #feign服务
    image: asdf1221/ofo-feign0:v0.1
    ports:
      - 8021:8021
    networks:
      - ofo-network
  ofo-feign1: #feign服务
    image: asdf1221/ofo-feign1:v0.1
    ports:
      - 8022:8022
    networks:
      - ofo-network
  ofo-feign2: #feign服务
    image: asdf1221/ofo-feign2:v0.1
    ports:
      - 8023:8023
    networks:
      - ofo-network
  ofo-hystrix-dashboard-turbine0: #hystrix-dashboard-turbine监控服务
    image: asdf1221/ofo-hystrix-dashboard-turbine0:v0.1
    ports:
      - 9001:9001
    networks:
      - ofo-network
  ofo-hystrix-dashboard-turbine1: #hystrix-dashboard-turbine监控服务
    image: asdf1221/ofo-hystrix-dashboard-turbine1:v0.1
    ports:
      - 9002:9002
    networks:
      - ofo-network
  ofo-gateway0: #网关服务
    image: asdf1221/ofo-gateway0:v0.2
    ports:
      - 7610:7610
    networks:
      - ofo-network
  ofo-gateway1: #网关服务
    image: asdf1221/ofo-gateway1:v0.2
    ports:
      - 7611:7611
    networks:
      - ofo-network
  ofo-gateway2: #网关服务
    image: asdf1221/ofo-gateway2:v0.2
    ports:
      - 7612:7612
    networks:
      - ofo-network
  ofo-web: #web页面
    image: asdf1221/ofo-web:v0.1
    ports:
      - 80:80
    networks:
      - ofo-network
#定义网络信息
networks:
  ofo-network:
    driver: bridge