server:
  port: 8011
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml     #mybatis配置文件路径
  type-aliases-package: com.cn.cloud.ofo.ofoapi.bean        #映射实体类包路径
  mapper-locations:
    - classpath:mybatis/xml/*.xml                    #数据库配置文件映射路径

spring:
  application:
    name: ofo-services
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ofo
    username: root
    password: 1234
    dbcp2:
      min-idle: 5           #数据库连接池最小可维持的连接数
      initial-size: 5       #初始化连接池的数量
      max-total: 3          #最大连接数
      max-wait-millis: 200  #获取连接的最大等待时间
  redis:      #redis配置
    client-name: localhost
    host: ofo-redis
    port: 6379
    database: 0
    password: as123456
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: 1000ms
        max-idle: 8
        min-idle: 8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: ofo-services8011     #在eureka注册中心的主机名称
    prefer-ip-address: true           #在eureka注册中心显示本实例的ip地址
info:       #自定义实例说明信息
  app.name: cloud-ofo-services
  company.name: null
  build.artifactId: $project.artifactId$
  build.verstion: $project.verstion$