server:
  port: 8083
eureka:
  instance:
    hostname: eureka2
  client: ##声明不向自己进行注册
    fetch-registry: false
    register-with-eureka: false
    service-url:
     # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #eureka集群
      defaultZone: http://eureka0:8081/eureka/,http://eureka1:8082/eureka/
  server:
    enable-self-preservation: true  #开启自我保护机制